# ==============================================================================
#                       tsync - Project Toolkit Configuration
# ==============================================================================
#
# Конфигурация для синхронизации toolkit компонентов в tsync проект.
# Используется для поддержания качества и консистентности кода.
#
# ==============================================================================

provider:
  url: "/home/xolinar/Workspace/Projects/FLUXGUARD/toolkit"
  version: "main"

vars:
  project_name: "tsync"
  project_description: "Система синхронизации toolkit для управления общими конфигурациями между проектами"
  github_org: "flux-guard"

sync:
  # ===========================================================================
  # Commit Quality
  # ===========================================================================
  - alias: "commitlint"
  - alias: "commitizen"
  - alias: "commits_deps"
  - alias: "commits_makefile"

  # ===========================================================================
  # Git
  # ===========================================================================
  - alias: "pre_commit"
  - alias: "gitattributes"

  # ===========================================================================
  # Build Automation
  # ===========================================================================
  - alias: "makefile_main"
  - alias: "makefile_help"

  # ===========================================================================
  # Editor
  # ===========================================================================
  - alias: "editorconfig"
  - alias: "vscode_settings"
  - alias: "vscode_extensions"
  - alias: "vscode_tasks"

  # ===========================================================================
  # Documentation
  # ===========================================================================
  - alias: "contributing"
  - alias: "code_of_conduct"
  - alias: "security_policy"

  # ===========================================================================
  # CI/CD Workflows
  # ===========================================================================
  - alias: "workflow_lint_commits"
  - alias: "workflow_release"
  - alias: "workflow_dependency_review"
  - alias: "workflow_auto_merge"
  - alias: "workflow_stale"
