name: Auto Merge

# ==============================================================================
# Назначение:
#   Автоматическое слияние PR от Dependabot и Renovate после прохождения CI.
# ==============================================================================

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  workflow_run:
    workflows: ["CI", "Go Lint", "Go Test"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    name: Auto Merge Dependabot/Renovate PRs
    runs-on: ubuntu-latest

    # Только для PR от ботов
    if: |
      github.actor == 'dependabot[bot]' ||
      github.actor == 'renovate[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            return {
              number: pr.number,
              author: pr.user.login,
              title: pr.title,
              labels: pr.labels.map(l => l.name)
            };

      - name: Wait for checks
        uses: fountainhead/action-wait-for-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: all
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Enable auto-merge for minor/patch updates
        if: |
          contains(github.event.pull_request.labels.*.name, 'dependencies') &&
          !contains(github.event.pull_request.labels.*.name, 'major-update')
        run: gh pr merge --auto --squash "$PR_NUMBER"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        if: |
          contains(github.event.pull_request.labels.*.name, 'dependencies') &&
          !contains(github.event.pull_request.labels.*.name, 'major-update')
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
